include:
  - project: cloud/integrations/ci
    file:
      - default.yml
      - workflows/feature-branches.yml
      - pre-commit.yml

stages:
  - test

pre-commit:
  extends: [.pre-commit]

test:
  stage: test
  image: golang:1.26
  variables:
    GOMODCACHE: $CI_PROJECT_DIR/.cache/go-mod
  cache:
    key:
      files: [go.mod, go.sum]
    paths: [$GOMODCACHE]
  before_script:
    - go get github.com/boumenot/gocover-cobertura@latest
    - go mod download
  script:
    - go test -coverprofile=coverage.txt -v -race ./...
    - mv coverage.txt coverage.tmp; grep -v '/zz_' coverage.tmp > coverage.txt; rm coverage.tmp
    - go run github.com/boumenot/gocover-cobertura < coverage.txt > coverage.xml
    - go tool cover -func=coverage.txt
  artifacts:
    paths:
      - coverage.txt
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
  coverage: /total:\s+\(statements\)\s+\d+.\d+%/
